// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCalculator.Data;

#nullable disable

namespace SimpleCalculator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240102125430_AddActionHistoryTable")]
    partial class AddActionHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleCalculator.Models.ActionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecuteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.ToTable("ActionHistory");
                });

            modelBuilder.Entity("SimpleCalculator.Models.CalculatorAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Operation")
                        .IsUnique();

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Perform addition",
                            Operation = "Addition"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Perform subtraction",
                            Operation = "Subtraction"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Perform division",
                            Operation = "Division"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Perform multiplication",
                            Operation = "Multiplication"
                        });
                });

            modelBuilder.Entity("SimpleCalculator.Models.ActionHistory", b =>
                {
                    b.HasOne("SimpleCalculator.Models.CalculatorAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");
                });
#pragma warning restore 612, 618
        }
    }
}
